name: Download Images (1 AM - 1 PM EDT)

on:
  schedule:
    - cron: "*/10 * * * *"
  workflow_dispatch:

jobs:
  download:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Download and commit in one script
        run: |
          set -e
          # 1) Time check
          current_hour=$(TZ="America/New_York" date +%H)
          current_hour=$(echo $current_hour | sed 's/^0*//')
          if [ "$current_hour" -lt 1 ] || [ "$current_hour" -ge 13 ]; then
            echo "Outside allowed time window. Exiting."
            exit 0
          fi

          # 2) Do the 10-minute loop
          for i in {1..10}; do
              echo "Iteration $i/10 at $(date)"
              tail -n +2 morning_cameras.csv | \
              while IFS=, read -r sign_location_name direction roadway camera_number url id || [ -n "$id" ]; do
                  echo "Processing camera: $id"
                  mkdir -p "$id"
                  ts=$(date +%s%3N)
                  timestamp=$(date '+%Y%m%d_%I%M%P')
                  outfile="${id}/${id}_${timestamp}.jpg"
                  curl "${url}?${ts}" -o "$outfile"
              done
              if [ $i -lt 10 ]; then
                  sleep 60
              fi
          done

          # 3) Commit and push
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add .
          if ! git diff-index --quiet HEAD; then
            git commit -m "Add images: $(date '+%Y-%m-%d %H:%M:%S') [skip ci]"
            git push origin HEAD:${GITHUB_REF#refs/heads/}
          else
            echo "No changes to commit."
          fi
